### ISSUE TITLE
Termux Running Error

### ISSUE THREAD

**Issue by marcustyj** [sriharshamvs/TelegramUserScraper#1]
Hi there, I run this script by using Android Termux, i believe there's no issues right? I having an error stated that : 

Traceback (most recent call last):
  File "scrapeSingleGroup.py", line 99, in <module>
    generateENV()
  File "scrapeSingleGroup.py", line 87, in generateENV
    data = input('{}: '.format(dataName[i]))
IndexError: list index out of range

Please let me know how to solve this error. i think is problem with the ENV.
Thanks

**Comment by sriharshamvs** [comment]
Hello,
I think the script should be working fine now.
There was an issue with list indexing. 
Updated section of the script
```python
for i in range(len(dataName)):
        data = input('{}: '.format(dataName[i]))
```
